var wishBrands = [
	"7 For All Mankind",
	"Abercrombie & Fitch",
	"Adidas",
	"Adler",
	"Alberta Ferretti",
	"Alberto Guardiani",
	"Aldo",
	"Alexander McQueen",
	"Alexander Wang",
	"Alice & Olivia",
	"American Apparel",
	"Armani",
	"Armani Exchange",
	"Asos",
	"Aspinal of London",
	"Atelier Versace",
	"Aveda",
	"Avon",
	"Balenciaga",
	"Balmain",
	"Banana Boat",
	"Banana Republic",
	"Barbour",
	"Bare Escentuals",
	"BareMinerals",
	"Barneys",
	"BB Dokota",
	"BCBG",
	"BDG",
	"birchbox",
	"Birkenstock",
	"Bobbi Brown",
	"Bottega Veneta",
	"Brian Atwood",
	"Bulgari",
	"Bumble & Bumble",
	"Burberry",
	"Burberry Prorsum",
	"Burresi",
	"Burt's Bees",
	"Butter London",
	"Bvlgari",
	"Calvin Klein",
	"Calvin Klein Jeans",
	"Calvin Klein Underwear",
	"Carla Zampatti",
	"Carmex",
	"Carolina Herrera",
	"Cartier",
	"Casio",
	"Celine",
	"Champneys",
	"Chanel",
	"chinese laundry",
	"Chloé",
	"Christian Cota",
	"Christian Dior",
	"Christian Louboutin",
	"Claire's",
	"Claire's Accessories",
	"Clarins",
	"Clarisonic",
	"Clarks Village",
	"Clinique",
	"Coach",
	"Coltorti",
	"Comme Des Garcons",
	"comptoir des cotonniers",
	"Converse",
	"Cortina Watch",
	"Coster Diamonds",
	"Costume National",
	"Covergirl",
	"creme de la mer",
	"Cruciani",
	"Cushnie et Ochs",
	"D&G",
	"d2jeans.com",
	"Dainty Doll",
	"Daisy Jewellery",
	"Daisy Street Shoes",
	"Daisystreet.co.uk",
	"day birger et mikkelsen",
	"De Beers",
	"de Bijenkorf",
	"de Grisogono",
	"De Nicola",
	"Dead Sea Spa",
	"Debenhams",
	"Debut at Debenhams",
	"Decleor",
	"Delfina Delettrez",
	"Delphine Manivet",
	"Denman",
	"Departmentstore Quartier 206",
	"Der Töpferladen",
	"Derek Lam",
	"Dermalogica",
	"Designer Outlet Roermond",
	"Desireclothing.com",
	"Diamond By Julien MacDonald",
	"Diane Von Furstenberg",
	"Dickson Watch & Jewellery",
	"Diecidecimi",
	"Diego Dolcini",
	"Diesel",
	"Dior",
	"Dior Couture",
	"Diptyque",
	"DKNY",
	"Doc Martens",
	"Dogeared",
	"Dolce & Gabana",
	"Dom & Ruby",
	"Donna Karan",
	"DooRi",
	"Dorotheum Juwelier",
	"Doux Me Neroli",
	"Dr Hauschka",
	"Dr Jart+",
	"Dr Martens",
	"Dr Oliver",
	"Dr Perricone",
	"Dr Sebagh",
	"Drake’s Couture Lingerie",
	"Dries Van Noten",
	"Dsquared2",
	"DV By Dolce Vita",
	"DVF",
	"E'Collezione",
	"Eckerle",
	"Edie Rose",
	"Egyptian Magic",
	"Eickhoff",
	"El Corte Inglés",
	"Elemis",
	"Eleven Paris",
	"Elie Saab",
	"Elie Saab Couture",
	"Elizabeth and James",
	"Elizabeth Arden",
	"Elle Macpherson Intimates",
	"Ellie Faas",
	"Elliot Rhodes",
	"Emilio Pucci",
	"Emin And Paul",
	"Eminence Organic Skincare",
	"Emporio Armani",
	"Emu",
	"Emu Astralia",
	"Enelle London",
	"Energie",
	"Enrapture",
	"EpiCentre",
	"Erdem",
	"Eric Bompard",
	"Erin Fetherston",
	"Ermanno Scervino",
	"Ermenegildo Zegna",
	"Ernest Jones",
	"Erotokritos",
	"Escada",
	"escentual.com",
	"Espace Temps",
	"esprit",
	"Essie",
	"Estée Lauder",
	"Etam",
	"Etro",
	"Eucerin",
	"evolvebeauty.co.uk",
	"F Pinet",
	"F&F at Tesco",
	"F+F",
	"Fabergé",
	"Fabi",
	"Fabriah.com",
	"Falguni & Shane Peacock",
	"Fashion-Conscience",
	"FashionistA",
	"Faust' Potions",
	"FCUK",
	"FDJ",
	"Fearne Cotton For Very.co.uk",
	"Feelunique.com",
	"Felipe Oliveria Baptista",
	"Fendi",
	"Fenwick",
	"Ferragamo",
	"Figleaves",
	"Filofax",
	"Fiorelli",
	"Fitriani",
	"Fnac",
	"Folli Follie",
	"Forever 21",
	"Fornarina",
	"Fortnum & Mason",
	"Franzen",
	"Frédéric Bellulo",
	"Frederic Fekkai",
	"Free People",
	"Freedom at Topshop",
	"Freeport Outlet",
	"French Connection",
	"French Sole",
	"Frette",
	"Freya",
	"FreyWille",
	"Frizzoni",
	"FrostFrench",
	"Funkyleisure.co.uk",
	"Furla",
	"Fydor Golan",
	"G Star",
	"G-Star Raw",
	"Galeria Kaufhof",
	"Galibardy.com",
	"Galizia",
	"Gap",
	"Gareth Pugh",
	"Garnier",
	"Gassan Diamonds",
	"gentlebodycare.co.uk",
	"Geo-skincare.co.uk",
	"Georg Jensen",
	"George at Asda",
	"George AW12",
	"GHD",
	"Gherardini",
	"Giambattista Valli",
	"Gianfranco Ferré",
	"Gianvito Rossi",
	"Gigivintage",
	"Gilan",
	"Giles",
	"Giles Deacon",
	"Gilles Fine Jewellery",
	"gillette",
	"Giorgio Armani",
	"Giorgio Armani Privé",
	"Giovanni Galli",
	"Giudecca 795 Art Gallery",
	"Giuseppe Zanotti",
	"Givenchy",
	"Givenchy by Riccardo Tisci",
	"Gizia",
	"Globus",
	"glossybox",
	"Gobbi 1842",
	"Goddiva",
	"Goldheart",
	"Görtz",
	"Gossard",
	"GrandOptical",
	"Gucci",
	"Gudrun",
	"Guerlain",
	"Guess",
	"Guess by Marciano",
	"Guinot",
	"GUiSHEM",
	"Guy Laroche",
	"H By Hudson",
	"H Samuel",
	"h! by henry holland",
	"H&M",
	"Hackett",
	"Hakaan",
	"H?mmerle",
	"Hanna Marie Hutchison",
	"Has Hal?",
	"Hasan Hejazi",
	"Hausmann",
	"Havaianas",
	"Havianas",
	"Hawes & Curtis",
	"Heathcote & Ivory",
	"Heavenly Oils",
	"hedonia",
	"Hei Poa",
	"Heinemann Duty Free",
	"Hellmann Mens Wear",
	"Hello Kitty",
	"Hello Kitty For Liberty",
	"Helmut Lang",
	"Hemtex",
	"Henleys",
	"Henry Holland",
	"Herbal Essences",
	"Hermès",
	"Hersheson",
	"Hervé Chapelier",
	"Herve L Leroux",
	"Herve Leger by Max Azria",
	"Herzo",
	"Hestermann & Sohn",
	"Heyraud",
	"Hobbs Cashmere",
	"Holland International Canal Cruises",
	"Hollister",
	"Holmes & Yang",
	"Hoola",
	"Hotiç",
	"House Of Dereon",
	"House of Fraser",
	"House of Harlow 1960",
	"House Of Holland",
	"House Of Holland, Christopher Kane",
	"House of Hung",
	"Howick",
	"HQHair",
	"Hublot",
	"Hübner",
	"Hudson",
	"Hugo Boss",
	"Igor Chapurin",
	"Il Bisonte",
	"Il Giglio",
	"Il Gufo",
	"Illamasqua",
	"Incase",
	"Internacionale",
	"Intersport",
	"Intraceuticals",
	"Isabel Marant",
	"Isabella Oliver",
	"Issey Miyake",
	"İstinye Park",
	"İtalgold",
	"Itsvintagedarling",
	"Izabel London",
	"J Brand",
	"J By Jasper Conran",
	"J Crew",
	"J Mendel",
	"J.W.Anderson",
	"J'Aton Couture",
	"Jacqueline Nerguizian",
	"Jacques Azagury",
	"Japonesque",
	"Jason Wu",
	"JD Sports",
	"Jean Charles De Castelbajac",
	"Jean Desses",
	"Jean Michel Cazabat",
	"Jeffrey Campbell",
	"Jelly Pong Pong",
	"Jellycat",
	"Jemma Kidd",
	"Jennewein Pure Sports",
	"Jergens",
	"Jewellery City",
	"Jewellery Time 2011",
	"Jexika",
	"Jil Sander",
	"Jimmy Choo",
	"JK Jemma Kidd",
	"Jo Hansford",
	"Jo Malone",
	"Joanne Stoker",
	"John Frieda",
	"John Galliano",
	"John Paul Gaultier",
	"Joico",
	"JonesandJonesfashion",
	"Joomi Lim",
	"Jouer",
	"Joules",
	"Joux Joux",
	"Jovonnista",
	"Juan Carlos Obando",
	"Judith Leiber",
	"Juicy Couture",
	"Julian J Smith",
	"Julie Haos",
	"Julien MacDonald",
	"Jun Ashida and Tae Ashida",
	"Juppen",
	"Jurlique",
	"Just Cavalli",
	"JW Anderson",
	"K by Karl Lagerfield",
	"Kalogirou",
	"Kandee",
	"Kangol",
	"KappAhl",
	"Kardashian Kollection",
	"Karl Lagerfeld",
	"Karstadt",
	"Kate Moss For Topshop",
	"Kate Sheridan",
	"Kate Spade",
	"katharine hamnett",
	"Katherine Hooker",
	"Kaufman Franco",
	"Keds",
	"Kekäle",
	"Kenneth Cole",
	"Kenzo",
	"kerastase",
	"Kerstin Florian",
	"Kettle & Kotch",
	"Kiehl's",
	"KIKO",
	"Kimchi & Blue",
	"Kipling",
	"Kiton",
	"Kleshna",
	"Klorane",
	"Klutch It by Kele",
	"Knize",
	"Koffer Klein",
	"Konen",
	"Konstantino jewellery",
	"Kooijman Souvenirs & Gifts",
	"Kookai",
	"Koton",
	"Kryolan",
	"Krystof Strozyna",
	"kuccia",
	"KUL-T",
	"Kwanpen",
	"L.A.M.B",
	"L.K Bennett",
	"L'Occitaine",
	"L'Oreal",
	"L'Oreal Paris",
	"L'Oreal Professionnel",
	"L'Wren Scott",
	"L’Agence",
	"L’Occitane",
	"L’Oréal",
	"L’Wren Scott",
	"La Clef des Marques",
	"La Gare 24",
	"La maison de l’Astronomie",
	"La Mer",
	"La Moda",
	"La Perla",
	"La Redoute",
	"la Rinascente",
	"La Roche-Posay",
	"La Scala Shop",
	"La Senza",
	"Lacoste",
	"Lacura",
	"Lanc",
	"Lancôme",
	"Lanidor",
	"Lanolips",
	"Lanvin",
	"Laqa & Co",
	"Lara Bohnic",
	"LaRare",
	"Laura Mercier",
	"Lavish Alice",
	"Lazy Lu",
	"LBC Home",
	"LC Waikiki",
	"Le Grand Bazar",
	"Le Tanneur",
	"Lefranc Ferrant",
	"Leica Stores Germany",
	"Leila Shams",
	"Leistenschneider",
	"Leo & Chloe",
	"Lepel",
	"LES AMBASSADEURS",
	"Les Néréides",
	"Levi's",
	"Liberty of London",
	"Lidl",
	"LifeFactory",
	"Lierac Paris",
	"Lindex",
	"Linea",
	"Linea Murano Art",
	"Links of London",
	"LINLEY",
	"linzi shoes",
	"Lipstick Queen",
	"Lipsy",
	"Littleblackdress.co.uk",
	"Littlewoods",
	"Liu Jo",
	"Liz Earle",
	"LK Bennett",
	"Lladró",
	"Lock & Co",
	"Loden-Frey",
	"Loden-Plankl",
	"Loewe",
	"Lola & Grace",
	"Lola Rose",
	"Longchamp",
	"Lookfantastic",
	"Lord & Berry",
	"Lorella",
	"Lorena Sarbu",
	"Loriblu",
	"Loro Piana",
	"Lorraine Schwartz",
	"Louis Vuitton",
	"Love Moschino",
	"Lovethybag",
	"Ludwig Beck",
	"Luella",
	"Luisa Beccaria",
	"Lulu & Co",
	"Lulu Frost",
	"Lyn Devon",
	"Magpul",
	"M-Boxi",
	"M&Co",
	"M&S",
	"MAC",
	"Macy's",
	"Madewell",
	"Maison de Bonneterie",
	"Maison Martin Margiela",
	"Malloni",
	"Mama Mio",
	"Mandalay",
	"Mango",
	"Manolo Blahnik",
	"Mappin & Webb",
	"Marc By Marc Jacobs",
	"Marc Jacobs",
	"Marchesa",
	"Marios Schwab",
	"Marithé + François Girbaud",
	"Matrix Essentials",
	"Max Azria",
	"Max Mara",
	"Max&Co.",
	"Maxfactor",
	"Maxim",
	"MaxMara",
	"Maybelline",
	"McQ by Alexander Mcqueen",
	"Meadham Kirchhoff",
	"Media Markt",
	"MEDIMAX",
	"Michael Kors",
	"Michael Van Der Ham",
	"Mientus",
	"Miguelina",
	"mih jeans",
	"Milly",
	"Minkpink",
	"Minnetonka",
	"missguided.co.uk",
	"Missoni",
	"Mitsukoshi",
	"Miu Miu",
	"Moda Galleria",
	"Moda in Pelle",
	"Moda Kamppi",
	"Modalu",
	"Modehaus Marion Heinrich",
	"Model Co.",
	"Moet & Chandon",
	"Monet",
	"Monique Lhuiller",
	"Monolo Blahnik",
	"Montblanc",
	"Mop C-System",
	"Moreschi",
	"Moschino",
	"Moser | Luxury Bohemian Crystal",
	"Motel at Topshop",
	"Motonet",
	"MQT Jeans",
	"MUA",
	"Mugler",
	"Mulberry",
	"MultiOpticas",
	"Muoti Moda",
	"Murphy&Nye",
	"My-Wardrobe.com",
	"Myfaceworks",
	"Myla",
	"Myslbek Shopping Gallery",
	"Mytights.com",
	"MYZONE",
	"N15",
	"Naeem Khan",
	"Nail Couture LA",
	"Nails Inc.",
	"Narciso Rodriguez",
	"Nars",
	"Neal And Wolf",
	"Necklaces",
	"Nelly.com",
	"Net a Porter",
	"NetWork",
	"Neurotica",
	"Nike",
	"Nina Ricci",
	"Nine West",
	"Nip + Fab",
	"Nivea",
	"NKO Cashmere",
	"nOir",
	"Nordstorm",
	"Notforponies.co.uk",
	"notosgalleries",
	"Notte By Marchesa",
	"Nubar",
	"Nutmeg's Jewellery",
	"Nuxe",
	"NW3 by Hobbs",
	"Nyla",
	"NYLA Boutique",
	"NYX",
	"O.P.I",
	"O'Neill",
	"Oasis",
	"Oberpollinger",
	"Obscure Couture",
	"Odalisque",
	"Oday Shakar",
	"Odd Molly",
	"Odeon",
	"Off Dutee",
	"Oger",
	"Ojon",
	"Olay",
	"Olcay Gulsen",
	"Ole Henriksen",
	"Oli.co.uk",
	"OMEGA",
	"Omo by Norma Kamali",
	"On Pedder",
	"Opening Ceremony",
	"OPI",
	"Optrex",
	"Ora Kessaris",
	"Orion",
	"Orly",
	"Orologeria Luigi Verga",
	"Oscar De La Renta",
	"Oscar Jacobson",
	"Osis",
	"Osman Yousefzada",
	"Ossie Clark",
	"Outletcity Metzingen",
	"Oxfam",
	"P J By Peter Jensen",
	"Paco Rabanne",
	"Palmers",
	"Pantene",
	"Paraboot",
	"Paris Miki",
	"Passionata",
	"Paul Mitchell",
	"Paulene Trigere",
	"Pedro del Hierro",
	"Pedro Lourenco",
	"Peek & Cloppenburg",
	"Peng Kwee Watches & Jewellery",
	"Penhaligon’s",
	"Penny Boutique",
	"Pepe Jeans",
	"Per Una",
	"Per-fekt",
	"Percy & Reed",
	"Perfumery Regia",
	"Peridot London",
	"Perricone MD",
	"Pharmacie Chaussée d’Antin",
	"Pharmacie Monge",
	"Pharmacie RER Port-Royal",
	"Phase Eight",
	"Phillip Lim",
	"Pied A Terre",
	"Pierre Hardy",
	"Pimkie",
	"Pink Label London",
	"Pinko",
	"Pisa Orologeria",
	"Pistol Panties",
	"Piumelli",
	"Pixmania",
	"POHLAND",
	"polo ralph lauren",
	"Poltock & Walsh",
	"Popcouture.co.uk",
	"Popp & Kretschmer",
	"Porsche Design",
	"Porsche Museum Shop",
	"Ports 1961",
	"Prada",
	"Precis Petite",
	"Pretaportobello.com",
	"Prettylittlething.com",
	"Primakr",
	"Pringle of Scotland",
	"Printmonkey",
	"Proenza Schouler",
	"Pronovias",
	"Pucci",
	"Pull & Bear",
	"Puma",
	"Punky Allsorts",
	"Pussy Willow",
	"Quicksilver",
	"Quintana Couture",
	"Quintessentially Travel",
	"QVC",
	"Rachel Gilbert",
	"Rachel Roy",
	"Rag & Bone",
	"Ralph Lauren",
	"Rare London",
	"Rare Zach",
	"Raspini",
	"Ray-Ban",
	"Rayban",
	"Re Mishelle",
	"Rebecca Minkoff",
	"Rebecca Taylor",
	"Rebel Nails",
	"Redken",
	"Reebok",
	"Reem Acra",
	"Regal Rose",
	"Revlon",
	"Reypenaer Proeflokaal",
	"RI Roksanda Ilincic",
	"Rigby & Peller",
	"Rimmel",
	"Rimmel London",
	"Rise Fashion",
	"River Island",
	"RM Trading",
	"RMK",
	"Robert Clergerie",
	"Robert Rodriguez",
	"Roberta By Olivia Palermo",
	"Roberto Botticelli",
	"Roberto Cavalli",
	"Rocha. John Rocha",
	"Rochas",
	"Rochester Big & Tall",
	"Rocket Dog",
	"rockmyvintage",
	"Rodarte",
	"Rodial",
	"Rolex",
	"Roxy",
	"Runway Route",
	"Saint Laurent",
	"Salone del Mobile",
	"Salvadori",
	"Salvatore Ferragamo",
	"Sam Edelman",
	"Samantha Thavasa",
	"Samsung",
	"Samsonite",
	"Samy Fat",
	"Sass & Bide",
	"Satori",
	"Schaap en Citroen",
	"Schlichting",
	"Schnitzler Perfumery",
	"Schuh",
	"Schustermann & Borenstein",
	"Schwarzkopf Professional",
	"See By Chloe",
	"Selfridges",
	"Sephora",
	"Sergio Rossi",
	"Serravalle Designer Outlet",
	"Sessun",
	"Shavata",
	"Shellac",
	"Shoedazzle",
	"Shoediction",
	"Shu Uemura",
	"Sienna X",
	"Silence + Noise",
	"Silkit",
	"Silly Bandz",
	"Simeon Farrar",
	"Simin",
	"Simon Spurr",
	"Simone Rocha",
	"Simonetta Ravizza",
	"Sincere Fine Watches",
	"SK-II",
	"SkinCeuticals",
	"Smashbox",
	"Soratte Outlet Shopping",
	"Spagnoletto",
	"Sportarena",
	"Sporthaus Münzinger",
	"Sporthaus Schuster",
	"sportmax",
	"St Pancras International",
	"St. Tropez",
	"Stadt-Parfümerie Pieper",
	"Star By Julien MacDonald",
	"Steamcream",
	"Stella McCartney",
	"stephane rolland",
	"Steve Madden",
	"Stila",
	"Stuart Weitzman",
	"Stylistpick.com",
	"Sunglass Hut",
	"Superdry",
	"Swatch",
	"T By Alexander Wang",
	"T Ristori",
	"T.M.Lewin",
	"TAG Heuer",
	"Temperley London",
	"Thakoon",
	"The Beauty Works",
	"The Beauty Works Ltd",
	"The Body Shop",
	"The North Face",
	"The Outnet",
	"The Row",
	"The Sanctuary",
	"theoutnet.com",
	"Thomas Pink",
	"Tibi",
	"Tiffany & Co",
	"tightsplease.co.uk",
	"TIGI",
	"Timberland",
	"TK Maxx",
	"Tod's",
	"Tom Ford",
	"Tommy Hilfiger",
	"Toms",
	"Toni & Guy",
	"Too Faced",
	"Topshop",
	"Topshop Boutique",
	"Topshop Limited Edition",
	"Topshop Makeup",
	"Topshop Unique",
	"Tory Burch",
	"TRESemmé",
	"Triumph Essence",
	"Tru Trussardi",
	"Trussardi",
	"Trussardi Jeans",
	"TU at Sainsbury's",
	"TW Steel",
	"Tweezerman",
	"Tweezers With Attitude",
	"Twenty8Twelve",
	"Twitter",
	"Tyco International",
	"Sensormatic",
	"Ugg",
	"Uniqlo",
	"Urban Decay",
	"Urban Outfitters",
	"Valentino",
	"Valentino Couture",
	"Van Cleef & Arpels",
	"Vans",
	"Vera Wang",
	"Versace",
	"Versace for H&M",
	"Versace Gioielli",
	"Victoria Beckham",
	"Victoria Victoria Beckham",
	"Victoria's Secret",
	"Virgin Atlantic",
	"Vita Coco",
	"Vita Liberata",
	"vivaladiva.com",
	"Vivienne Westwood",
	"Wildfang",
	"Wildfox",
	"Windle & Moodie",
	"Winter Kate",
	"Wolford",
	"YSL",
	"Yves Rocher",
	"Yves Saint Laurent",
	"Zac Posen",
	"Zandra Rhodes",
	"Zara"
];




//尺寸的数据结构
var sizeData = {
	 Man    :{
		head:  '<div class="col-xs-12" id="sizeAdd"><table class="chicunTab table table-bordered"><thead>' +
				'<tr><th rowspan="2"></th><th colspan="2" style="text-align:center"">Chest</th><th colspan="2" style="text-align:center">Waist</th><th colspan="2" style="text-align:center">Neck</th><th colspan="2" style="text-align:center">Sleeve</th></tr>' + 
				'<tr class="text-center"><td>厘米</td><td>英寸</td><td>厘米</td><td>英寸</td><td>厘米</td><td>英寸</td><td>厘米</td><td>英寸</td></tr>' +
					'</thead><tbody>',
		tpl :   '<tr>' +
				'<td><label><input type="checkbox" name="Man" value="&{code_size}"> &{size}</label></td>' +
				'<td>&{chestA}</td>' +
				'<td>&{chestB}</td>' +
				'<td>&{waistA}</td>' +
				'<td>&{waistB}</td>' +
				'<td>&{neckA}</td>' +
				'<td>&{neckB}</td>' +
				'<td>&{sleeveA}</td>' +
				'<td>&{sleeveB}</td>' +
				'</tr>',
		foot : '</tbody></table></div>',
		data : [
		{size:'XS',chestA:'76 - 81(cm)',chestB:'30" - 32"',waistA:'61 - 66(cm)',waistB:'24" - 26"',neckA:'33 - 34(cm)',neckB:'13" - 13.5"',sleeveA:'79 - 81(cm)',sleeveB:'31" - 32"'},
		{size:'S',chestA:'86 - 91(cm)',chestB:'34" - 36"',waistA:'71 - 76(cm)',waistB:'28" - 30"',neckA:'36 - 37(cm)',neckB:'14" - 14.5"',sleeveA:'81 - 84(cm)',sleeveB:'32" - 33"'},
		{size:'M',chestA:'97 - 102(cm)',chestB:'38" - 40"',waistA:'81 - 86(cm)',waistB:'32" - 34"',neckA:'33 - 34(cm)',neckB:'15" - 15.5"',sleeveA:'84 - 86(cm)',sleeveB:'33" - 34"'},
		{size:'L',chestA:'107 - 112(cm)',chestB:'42" - 44"',waistA:'91 - 97(cm)',waistB:'36" - 38"',neckA:'41 - 42(cm)',neckB:'16" - 16.5"',sleeveA:'86 - 89(cm)',sleeveB:'34" - 35"'},
		{size:'XL',chestA:'117 - 122(cm)',chestB:'46" - 48"',waistA:'102 - 107(cm)',waistB:'40" - 42"',neckA:'43 - 44(cm)',neckB:'17" - 17.5"',sleeveA:'89 - 91(cm)',sleeveB:'35" - 36"'},
		{size:'XXL',chestA:'127 - 132(cm)',chestB:'50" - 52"',waistA:'112 - 117(cm)',waistB:'44" - 46"',neckA:'46 - 47(cm)',neckB:'18" - 18.5"',sleeveA:'91 - 94(cm)',sleeveB:'36" - 37"'},
		{size:'XXXL',chestA:'137 - 142(cm)',chestB:'54" - 56"',waistA:'122 - 127(cm)',waistB:'48" - 50"',neckA:'48 - 50(cm)',neckB:'19" - 19.5"',sleeveA:'94 - 97(cm)',sleeveB:'37" - 38"'},
		{size:'XXXXL',chestA:'147 - 152(cm)',chestB:'58" - 60"',waistA:'132 - 137(cm)',waistB:'52" - 54"',neckA:'51 - 52(cm)',neckB:'20" - 20.5"',sleeveA:'97 - 99(cm)',sleeveB:'38" - 39"'},
		{size:'XXXXXL',chestA:'157 - 163(cm)',chestB:'62" - 64"',waistA:'142 - 147(cm)',waistB:'56" - 58"',neckA:'53 - 55(cm)',neckB:'21" - 21.5"',sleeveA:'99 - 102(cm)',sleeveB:'39" - 40"'}
		]
	},
	Women    : {
		head :	'<div class="col-xs-12" id="sizeAdd"><table class="chicunTab table table-bordered"><thead><tr><th rowspan="2"></th><th colspan="2" style="text-align:center">Bust/Chest</th><th colspan="2" style="text-align:center">Waist</th><th colspan="2" style="text-align:center">Hip</th></tr><tr class="text-center"><td>厘米</td><td>英寸</td><td>厘米</td><td>英寸</td><td>厘米</td><td>英寸</td></tr></thead><tbody>',
		tpl  :	'<tr>' + 
				'<td><label><input type="checkbox" name="Women" value="&{code_size}"> &{size}</label></td>' +
				'<td>&{bustA}</td>' +
				'<td>&{bustB}</td>' +
				'<td>&{waistA}</td>' +
				'<td>&{waistB}</td>' +
				'<td>&{hipA}</td>' +
				'<td>&{hipB}</td>' +
				'</tr>',
		foot :	'</tbody></table></div>',
		data : [{size:'XXS',bustA:'80 - 83(cm)',bustB:'31.5" - 32.5"',waistA:'60 - 62(cm)',waistB:'23.5" - 24.5"',hipA:'86 - 89(cm)',hipB:'34" - 35"'},{size:'XS',bustA:'83 - 85(cm)',bustB:'32.5" - 33.5"',waistA:'62 - 65(cm)',waistB:'24.5" - 25.5"',hipA:'89 - 91(cm)',hipB:'35" - 36"'},{size:'S',bustA:'85 - 88(cm)',bustB:'33.5" - 34.5"',waistA:'65 - 67(cm)',waistB:'25.5" - 26.5"',hipA:'91 - 94(cm)',hipB:'36" - 37"'},{size:'M',bustA:'90 - 93(cm)',bustB:'35.5" - 36.5"',waistA:'70 - 72(cm)',waistB:'27.5" - 28.5"',hipA:'97 - 99(cm)',hipB:'38" - 39"'},{size:'L',bustA:'97 - 100(cm)',bustB:'38" - 39.5"',waistA:'76 - 80(cm)',waistB:'30" - 31.5"',hipA:'103 - 107(cm)',hipB:'40.5" - 42"'},{size:'XL',bustA:'104 - 109(cm)',bustB:'41" - 43"',waistA:'84 - 88(cm)',waistB:'33" - 34.5"',hipA:'110 - 116(cm)',hipB:'43.5" - 45.5"'},{size:'XXL',bustA:'110 - 116(cm)',bustB:'43.5" - 45.5"',waistA:'91 - 95(cm)',waistB:'36" - 37.5"',hipA:'116 - 123(cm)',hipB:'45.5" - 48.5"'}]
	},
	Child    : {
		head :'<div class="col-xs-12" id="sizeAdd">',
		tpl  :'<div class="col-xs-4"><label>'+
			  '<input type="checkbox" name="Child" value="&{code_size}"> &{size}'+
			  '</label></div>',
		foot :'</div>',
		data :[{size:'Newborn'},{size:'0-3m'},{size:'4-5 Years'},{size:'2t'},{size:'0-6m'},{size:'5-6 Years'},{size:'3t'},{size:'3-6m'},{size:'6-7 Years'},{size:'4t'},{size:'6-12m'},{size:'7-8 Years'},{size:'5t'},{size:'6-9m'},{size:'8-9 Years'},{size:'6t'},{size:'9-12m'},{size:'9-10 Years'},{size:'7t'},{size:'12-18m'},{size:'10-11 Years'},{size:'8t'},{size:'18-24m'},{size:'11-12 Years'},{size:'6 Months'},{size:'1-2 Years'},{size:'12-13 Years'},{size:'12 Months'},{size:'2-3 Years'},{size:'13-14 Years'},{size:'18 Months'},{size:'3-4 Years'},{size:'14-15 Years'}]
	},
	ChildShoes    : {
		head :'<div class="col-xs-12" id="sizeAdd">',
		tpl  :'<div class="col-xs-4"><label>'+
			  '<input type="checkbox" name="Child" value="&{code_size}"> &{size}'+
			  '</label></div>',
		foot :'</div>',
		data :[{size:'7 - 8'},{size:'11 - 12'},{size:'2 - 3'},{size:'9 - 10'},{size:'13 - 1'}]
	},
	Bras     : {
		head :'<div class="col-xs-12" id="sizeAdd">',
		tpl  :'<div class="col-xs-4"><label>'+
			  '<input type="checkbox" name="Bras" value="&{code_size}"> &{size}'+
			  '</label></div>',
		foot :'</div>',
		data :[{size:'30B'},{size:'34D'},{size:'38D'},{size:'30C'},{size:'34DD'},{size:'38DD'},{size:'30D'},{size:'34DDD'},{size:'38DDD'},{size:'32A'},{size:'36A'},{size:'40B'},{size:'32AA'},{size:'36AA'},{size:'40C'},{size:'32B'},{size:'36B'},{size:'40D'},{size:'32C'},{size:'36C'},{size:'40DD'},{size:'32D'},{size:'36D'},{size:'40DDD'},{size:'32DD'},{size:'36DD'},{size:'42D'},{size:'32DDD'},{size:'36DDD'},{size:'42DD'},{size:'34A'},{size:'38A'},{size:'42DDD'},{size:'34AA'},{size:'38B'},{size:'44DD'},{size:'34B'},{size:'38C'},{size:'44DDD'},{size:'34C'}]
	},
	AdditionalApparelSizes     : {
		head :'<div class="col-xs-12" id="sizeAdd">',
		tpl  :'<div class="col-xs-4"><label>'+
			  '<input type="checkbox" name="AdditionalApparelSizes" value="&{code_size}"> &{size}'+
			  '</label></div>',
		foot :'</div>',
		data :[{size:'One Size'},{size:'1X'},{size:'Youth M(10-12)'},{size:'XXXS'},{size:'2X'},{size:'Youth S(6-8)'},{size:'6XL'},{size:'3X'},{size:'Adult'},{size:'7XL'},{size:'Youth XL(16-18)'},{size:'Kid'},{size:'8XL'},{size:'Youth L(14-16)'}]
	},
	Shoes    : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Shoes" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div><div class="col-xs-12"><div class="col-xs-5"><label>其他:</label><input type="text"    id="newShoesSize"> <button class="btn btn-default disabled btn-sm newShoesSize" type="button">添加</button></div></div>',
		data : [{size:'0'},{size:'7'},{size:'14'},{size:'0.5'},{size:'7.5'},{size:'14.5'},{size:'1'},{size:'8'},{size:'15'},{size:'1.5'},{size:'8.5'},{size:'15.5'},{size:'2'},{size:'9'},{size:'16'},{size:'2.5'},{size:'9.5'},{size:'16.5'},{size:'3'},{size:'10'},{size:'17'},{size:'3.5'},{size:'10.5'},{size:'17.5'},{size:'4'},{size:'11'},{size:'18'},{size:'4.5'},{size:'11.5'},{size:'18.5'},{size:'5'},{size:'12'},{size:'19'},{size:'5.5'},{size:'12.5'},{size:'19.5'},{size:'6'},{size:'13'},{size:'20'},{size:'6.5'},{size:'13.5'},{size:'20.5'}]
	},
	Bedding  : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Bedding" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div>',
		data : [{size:'Single'},{size:'Full'},{size:'Super King'},{size:'Twin'},{size:'Queen'},{size:'California King'},{size:'Double'},{size:'King'}]
	},
	Macbooks : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Macbooks" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div>',
		data : [{size:'11" Macbook'},{size:'13" MacBook Air'},{size:'15" Macbook Pro'},{size:'11" MacBook Air'},{size:'15" MacBook Air'},{size:'15" MacBook Pro with Retina display'},{size:'12" MacBook'},{size:'13" MacBook Pro'},{size:'17" Macbook Pro'},{size:'13" White MacBook'},{size:'13" MacBook Pro with Retina display'}]
	},
	Smartphones : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Smartphones" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div>',
		data : [{size:'Apple Watch 38mm'},{size:'Samsung Galaxy A5'},{size:'SONY Xperia Z2'},{size:'Apple Watch 42mm'},{size:'Samsung Galaxy A7'},{size:'SONY Xperia Z2 tablet'},{size:'iPod Touch 4'},{size:'Samsung Galaxy A8'},{size:'SONY Xperia Z3'},{size:'iPod Touch 5'},{size:'Samsung Galaxy J1'},{size:'SONY Xperia Z3 Mini'},{size:'iPad Mini'},{size:'Samsung Galaxy Alpha G850'},{size:'SONY Xperia Z4'},{size:'iPad Mini 2'},{size:'Samsung Galaxy Mega 5.8'},{size:'LG NEXUS 5'},{size:'iPad Mini 3'},{size:'Samsung Galaxy Mega 2'},{size:'LG G2'},{size:'iPad Mini 4'},{size:'Samsung Galaxy Grand Neo'},{size:'LG G3'},{size:'iPad Air'},{size:'Samsung Galaxy Grand Prime'},{size:'LG G4'},{size:'iPad Air 2'},{size:'Samsung Galaxy Grand 2'},{size:'LG G Stylo'},{size:'iPad 1'},{size:'Samsung Galaxy Core Max'},{size:'LG L40'},{size:'iPad 2'},{size:'Samsung Galaxy Grand Prime LTE G530H G530F'},{size:'LG L70'},{size:'iPad 3'},{size:'Samsung Galaxy Core Prime G360P'},{size:'LG L80'},{size:'iPad 4'},{size:'Samsung Google Nexus 10'},{size:'LG L90'},{size:'iPhone 4'},{size:'Amazon Kindle'},{size:'LG Tribute 2 Leon C40'},{size:'iPhone 4s'},{size:'Amazon Kindle 2'},{size:'LG L15G'},{size:'iPhone 5'},{size:'Amazon Kindle DX'},{size:'LG Lancet VW820'},{size:'iPhone 5c'},{size:'Amazon Kindle Keyboard'},{size:'LG Magna H502G VOLT 2'},{size:'iPhone 5s'},{size:'Amazon Kindle 4'},{size:'LG Revere 3 / VN170'},{size:'iPhone 6'},{size:'Amazon Kindle Fire'},{size:'Nokia Lumia 640'},{size:'iPhone 6 Plus'},{size:'Amazon Kindle Fire PaperWhite'},{size:'Nokia Lumia 930'},{size:'iPhone 6S'},{size:'Amazon Kindle Touch'},{size:'Motorola Moto G'},{size:'iPhone 6S Plus'},{size:'Amazon Kindle Fire HD 7in'},{size:'Motorola Moto G2'},{size:'Samsung Galaxy S2'},{size:'Amazon Kindle Fire HD 8.9in'},{size:'Motorola Moto G3'},{size:'Samsung Galaxy S3'},{size:'Amazon Kindle Paperwhite'},{size:'Motorola Moto X'},{size:'Samsung Galaxy S3 Mini'},{size:'Amazon Kindle Voyage'},{size:'Motorola Moto X Style Pure Edition'},{size:'Samsung Galaxy S4 Mini'},{size:'HTC M7'},{size:'Microsoft Surface RT Pro'},{size:'Samsung Galaxy S4'},{size:'HTC M8'},{size:'iOS'},{size:'Samsung Galaxy S5 Mini'},{size:'HTC M9'},{size:'Huawei Ascend P6'},{size:'Samsung Galaxy S5'},{size:'HTC One Max'},{size:'Huawei Ascend P7'},{size:'Samsung Galaxy S5 Active'},{size:'HTC One Mini 2'},{size:'Huawei Ascend Mate 7'},{size:'Samsung Galaxy S5 (E5000)'},{size:'HTC One M8 Mini'},{size:'Huawei Ascend G530'},{size:'Samsung Galaxy S6'},{size:'HTC One M9'},{size:'Huawei Honor 6'},{size:'Samsung Galaxy S6 Active'},{size:'HTC One M9+'},{size:'Huawei Honor 3c'},{size:'Samsung Galaxy S6 Edge'},{size:'HTC One E8'},{size:'Huawei Raven LTE H892L'},{size:'Samsung Galaxy S6 Edge Plus'},{size:'HTC One E9'},{size:'Huawei Pronto LTE SnapTO H891L G620'},{size:'Samsung Galaxy Mega 6.3'},{size:'HTC One E9+'},{size:'Huawei Tribute Fusion 3 Y536'},{size:'Samsung Galaxy Note Edge N9150'},{size:'HTC Desire 626'},{size:'XiaoMi Mi 3'},{size:'Samsung Galaxy Note 1'},{size:'HTC Desire 816'},{size:'XiaoMi Mi 4'},{size:'Samsung Galaxy Note 2'},{size:'HTC Desire 820'},{size:'XiaoMi RedMi'},{size:'Samsung Galaxy Note 3'},{size:'HTC Desire 826'},{size:'XiaoMi RedMi Note'},{size:'Samsung Galaxy Note 3 Lite N7506'},{size:'SONY 339H'},{size:'Android'},{size:'Samsung Galaxy Note 3 Neo'},{size:'SONY L36H'},{size:'Kyocera Hydro Wave C6740'},{size:'Samsung Galaxy Note 4'},{size:'SONY L39H'},{size:'Alcatel onetouch Pop Astro 5042T'},{size:'Samsung Galaxy Note 5'},{size:'SONY L39U'},{size:'Alcatel Pop Icon 2 A846L'},{size:'Samsung Galaxy Note 8.0'},{size:'SONY Xperia C3'},{size:'Asus Zenfone 2e'},{size:'Samsung Galaxy Note 10'},{size:'SONY Xperia E3'},{size:'ZTE LEVER Z936L'},{size:'Samsung Galaxy Tab 4.7in'},{size:'SONY Xperia M2'},{size:'ZTE Speed/N9130'},{size:'Samsung Galaxy Tab 4.8in'},{size:'SONY Xperia T2 Ultra'},{size:'ZTE Warp Elite N9518'},{size:'Samsung Galaxy A3'},{size:'SONY Xperia T3'},{size:'ZTE Zephyr Z752C SONATA 2'}]
	},
	Gaming   : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Gaming" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div>',
		data : [{size:'Playstation 3 Slim'},{size:'Playstation 3 Slim 1'},{size:'Playstation 3 Original 1'},{size:'Playstation 3 Original'},{size:'Playstation 3 Slim 2'},{size:'Playstation 3 Original 2'}]
	},
	Headphones : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Headphones" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div>',
		data : [{size:'Beats Pro'},{size:'Beats Solo 2 Wireless'},{size:'Beats Studio 2013+ Models'},{size:'Beats Solo'},{size:'Beats Solo-HD'},{size:'Beats MIXR'},{size:'Beats Solo 2'},{size:'Beats Studio'},{size:'Beats Wireless'}]
	},
	Memory   : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Memory" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div>',
		data : [{size:'1GB'},{size:'16GB'},{size:'256GB'},{size:'2GB'},{size:'32GB'},{size:'512GB'},{size:'4GB'},{size:'64GB'},{size:'1TB'},{size:'8GB'},{size:'128GB'}]
	},
	Voltage  : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '',
		foot : '</div><div class="col-xs-12"><div class="col-xs-5"><label>例子:100V,50v</label><br><label>其它:</label><input type="text" class="mTop20" id="newVoltageSize"> <button class="btn btn-default disabled btn-sm newVoltageSize" type="button">添加</button></div></div>',
		data : []
	},
	Area     : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '',
		foot : '</div><div class="col-xs-12"><div class="col-xs-6">'+
			   '<label>例子:1.4m x 1.4m,10.5"*10.5",10cm by 10cm by 10cm'+
			   '</label><br><label>其它:</label><input type="text" class="mTop20" id="newAreaSize"> <button class="btn btn-default disabled btn-sm newAreaSize" type="button">添加</button></div></div>',
		data : []
	},
	Length   : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '',
		foot : '</div><div class="col-xs-12"><div class="col-xs-5"><label>例子:6\'5",10m,5",11.5cm,6ft 5in</label><br><label>其它:</label><input type="text" class="mTop20" id="newLengthSize"> <button class="btn btn-default disabled btn-sm newLengthSize" type="button">添加</button></div></div>',
		data : []
	},
	Weight   : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '',
		foot : '</div><div class="col-xs-12"><div class="col-xs-5"><label>例子:100kg,11.5lb,3.14g</label><br><label>其它:</label><input type="text" class="mTop20" id="newWeightSize"> <button class="btn btn-default disabled btn-sm newWeightSize" type="button">添加</button></div></div>',
		data : []
	},
	Numbers  : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Numbers" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div><div class="col-xs-12"><div class="col-xs-5"><label>其他:</label><input type="text" class="mTop20" id="newNumbersSize"> <button class="btn btn-default disabled btn-sm newNumbersSize" type="button">添加</button></div></div>',
		data : [{size:'0'},{size:'7'},{size:'14'},{size:'0.5'},{size:'7.5'},{size:'14.5'},{size:'1'},{size:'8'},{size:'15'},{size:'1.5'},{size:'8.5'},{size:'15.5'},{size:'2'},{size:'9'},{size:'16'},{size:'2.5'},{size:'9.5'},{size:'16.5'},{size:'3'},{size:'10'},{size:'17'},{size:'3.5'},{size:'10.5'},{size:'17.5'},{size:'4'},{size:'11'},{size:'18'},{size:'4.5'},{size:'11.5'},{size:'18.5'},{size:'5'},{size:'12'},{size:'19'},{size:'5.5'},{size:'12.5'},{size:'19.5'},{size:'6'},{size:'13'},{size:'20'},{size:'6.5'},{size:'13.5'},{size:'20.5'}]
	},
	Volume   : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '',
		foot : '</div><div class="col-xs-12"><div class="col-xs-5"><label>例子:100mL,200L,40 fl.oz.,10.5pt</label><br><label>其它:</label><input type="text" class="mTop20" id="newVolumeSize"> <button class="btn btn-default disabled btn-sm newVolumeSize" type="button">添加</button></div></div>',
		data : []
	},
	Shapes   : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Shapes" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div>',
		data : [{size:'Pearl'},{size:'Heart'},{size:'Basic'},{size:'Cubic'},{size:'Rose'},{size:'Twist'}]
	},
	Others   : {
		head : '<div class="col-xs-12" id="sizeAdd">',
		tpl  : '<div class="col-xs-4"><label>'+
			   '<input type="checkbox" name="Others" value="&{code_size}"> &{size}'+
			   '</label></div>',
		foot : '</div>',
		data : [{size:'MousePad Foam Backed'},{size:'Pack of 4'},{size:'Pack of 6'},{size:'MousePad Stick it'}]
	}
};


//color
var goodsColorData = [
{name:"白色",rgb:"#ffffff",colorId:"white",class:"fBlack"},
{name:"黑色",rgb:"#000000",colorId:"black"},
{name:"红色",rgb:"#FF2600",colorId:"red"},
{name:"蓝色",rgb:"#0433FF",colorId:"blue"},
{name:"绿色",rgb:"#009051",colorId:"green"},
{name:"灰色",rgb:"#797979",colorId:"grey"},
{name:"棕色",rgb:"#941100",colorId:"brown"},
{name:"黄褐",rgb:"#929000",colorId:"tan"},
{name:"米黄",rgb:"#FFFFCC",colorId:"beige",class:"fBlack"},
{name:"粉红",rgb:"#FF2F92",colorId:"pink"},
{name:"橙色",rgb:"#FF9300",colorId:"orange"},
{name:"黄色",rgb:"#FFFB00",colorId:"yellow",class:"fBlack"},
{name:"乳白",rgb:"#EBEBEB",colorId:"ivory",class:"fBlack"},
{name:"墨绿",rgb:"#005493",colorId:"jasper"},
{name:"紫色",rgb:"#531B93",colorId:"purple"},
{name:"金色",rgb:"#FFD479",colorId:"gold"},
{name:"多彩",rgb:"url('/images/multicolor.jpg') repeat-y",colorId:"multicolor"}
];
 
//其他颜色
var otherColorDataB = ["fawn","frenchlilac","darkraspberry","pinklavender","copperpenny","brightnavyblue","chamoisee","paleplum","forestcamouflage","olive","darkseagreen","frenchbeige","metallicbronze","rosetaupe","darkchestnut","orangepeel","desertsand","lightkhaki","palebrown","mintcream","grape","gold","fashionfuchsia","mountainmeadow","dutchwhite","fushcia","uclablue","lapislazuli","telemagenta","chinapink","neonred","illuminatingemerald","rhythm","darkspringgreen","crimson","islamicgreen","regalia","pastelred","greyishwhite","darklavender","brown","green-yellow","imperialred","barnred","mattewhite","outrageousorange","carrotorange","veronica","fluorescentorange","darktaupe","portlandorange","tangerineyellow","cyan","bubbles","cobalt","peridot","richelectricblue","skyblue","frenchskyblue","littleboyblue","brinkpink","asparagus","darkgray","mediumspringbud","moccasin","platinum","lightpink","sand","caribbeangreen","red","northtexasgreen","purpletaupe","bulgarianrose","olivine","claret","purplefuchsia","japaneseindigo","steelblue-purple","chinarose","lightgoldenrodyellow","almond","deepcoffee","lavender","wildblueyonder","neongreen","wheat","stildegrainyellow","blue","yelloworange","newcar","magnolia","zebraprint","sangria","burgundy","purplishred","rossocorsa","chromeyellow","carolinablue","pinksherbet","rustbrown","frenchlime","kucrimson","deepcerise","deepskyblue","sunglow","pucered","darkvanilla","nadeshikopink","brightcerulean","yankeesblue","kenyancopper","jasmine","mountbattenpink","lemonlime","red-brown","russianviolet","ufogreen","oldmauve","roseebony","cadmiumgreen","electricviolet","flavescent","purplemountainmajesty","floralwhite","yellowcamouflage","vividviolet","flamingopink","metallicsilver","azuremist","gray-blue","cinnamon","antiquebronze","lightredochre","palespringbud","sacramentostategreen","deepmossgreen","mughalgreen","lemoncurry","golden","rubyred","spartancrimson","greenplaid","straw","frenchbistre","lightseagreen","purpleheart","off-white","sienna","vividcerise","skyblueorange","purplepizzazz","rawumber","cameopink","rosewood","gamboge","copperred","ebony","lime","whitedyedip","princetonorange","shockingpink","bluesapphire","winered","royalblue","lakeblue","lavendermagenta","tuscan","pearl","capri","frenchblue","freshair","palecarmine","blueberry","cerise","chestnut","blue-gray","brightgreen","lightyellow","mikadoyellow","pastelviolet","tangerine","flax","lemonchiffon","chocolate","melon","cordovan","aquablue","darkgrey","psychedelicpurple","catawba","mediumcarmine","fandangopink","darktangerine","silvergreen","antiquewhite","tiger'seye","paletaupe","baker-millerpink","patriarch","darkslateblue","lightskyblue","sandstorm","rufous","lumber","languidlavender","deeppink","fandango","pumpkin","plum","palered-violet","bittersweet","timberwolf","paleturquoise","lightbrown","dodgerblue","honolulublue","liverchestnut","navypurple","magenta","tan","mediumruby","pink","purplelight","vividauburn","blackfuchsia","safetyyellow","pistachio","persimmon","jellybean","khakigreen","orange-red","mellowapricot","giantsorange","mangotango","cardinal","rose","cheetah","palecerulean","midnightblue","richcarmine","coralpink","purplenavy","yellowrose","darkjunglegreen","transparentwhite","brightube","mordantred19","non-photoblue","darkliver","fuchsia-black","lightslategray","operamauve","floral","magentahaze","japaneseviolet","camelbrown","rubinered","mediumseagreen","lightgray","smoke","heliotrope","tractorred","cadetblue","bluebell","ultramarineblue","mayablue","silverwhite","ruddybrown","ticklemepink","linen","lightleopard","green","lighttan","powderblue","bluebonnet","tiffanyblue","peachpuff","cherrypink","wine","babypink","kombugreen","mediumviolet-red","tuscantan","darkcoral","smokyblack","nacarat","yellow-green","italianskyblue","usccardinal","violet-red","sandytaupe","electricindigo","cambridgeblue","khakibeige","lavendermist","darkimperialblue","shamrockgreen","indigodye","razzmatazz","malachite","screamin'green","silverpink","sealbrown","mediumblue","electriclime","orange","lincolngreen","lasallegreen","canaryyellow","antiqueblack","smalt","coffee","lemonyellow","aurometalsaurus","brandeisblue","pinkpearl","englishviolet","mossgreen","upmaroon","pastelorange","dollarbill","pink-orange","winedregs","persianrose","wildorchid","fuchsiarose","jonquil","pastelyellow","cocoa","candypink","goldenrod","catalinablue","uablue","razzmicberry","tiger","sunset","brightmaroon","dukeblue","ecru","deeptaupe","radicalred","safetyorange","wildwatermelon","darkmagenta","applegreen","utahcrimson","oldmossgreen","bone","brightred","hansayellow","tumbleweed","pastelblue","lilac","reddevil","mahogany","orangeplaid","genericviridian","mediumturquoise","multicolored","mediumtaupe","zebra","queenblue","navy","cadmiumyellow","trolleygrey","oceanboatblue","sandy","celestialblue","olivegreen","darkarmygreen","darkplum","navajowhite","deeptuscanred","milkwhite","richlavender","huntergreen","lightpurple","darkkhaki","palatinatepurple","seablue","stizza","peach-yellow","amaranth","amethyst","steelpink","uscgold","lightcarminepink","cornsilk","independence","ruddy","slategray","ferrarired","donkeybrown","acidgreen","dirt","leopard","bistre","paoloveronesegreen","crimsonglory","steelblue","gray-asparagus","magicmint","rosepink","carnelian","aliceblue","copperrose","schausspink","gainsboro","waterblue","riflegreen","feldgrau","phthalogreen","palepink","inkblue","lightgrey","lightcyan","alizarincrimson","darksalmon","rocketmetallic","bleudefrance","lavenderpurple","blush","mediumjunglegreen","teagreen","burntorange","copper","puce","unmellowyellow","licorice","limerick","tuftsblue","coolgrey","mistyrose","upforestgreen","kobi","ambergold","electricgreen","darksienna","kobe","eminence","imperial","glitter","skymagenta","darkyellow","lavenderindigo","hollywoodcerise","jet","springbud","burlywood","red-violet","terracotta","carminepink","richblack","electricultramarine","camouflagegreen","laserlemon","spanishorange","periwinkle","cinereous","purpureus","transparentred","darkskyblue","tomato","darktan","cadmiumred","laurelgreen","neonfuchsia","heathergray","palechestnut","englishlavender","denimblue","greenapple","greenlight","lightsalmon","richmaroon","flattery","darkelectricblue","iceberg","hotpink","raspberry","limegreen","darkpastelgreen","pear","peacockblue","celadon","darkscarlet","blue-violet","flame","fireenginered","goldfusion","lightsalmonpink","goldenyellow","coconut","persianblue","titaniumyellow","androidgreen","washedblack","pansypurple","olivegreenblack","ginger","payne'sgrey","lightgreen","persianplum","blond","cgblue","romansilver","mint","pastelbrown","byzantine","whitesmoke","lightblue","violet-blue","richbrilliantlavender","fluorescentrose","raspberryrose","tulip","deepmagenta","vegasgold","snow","camouflage","tropicalrainforest","mediumelectricblue","bananayellow","rajah","zomp","fluorescentpink","raspberrypink","unbleachedsilk","soap","transparent","yellowlight","silverchalice","lemonglacier","oldsilver","salmon","antiquesilver","harvestgold","mediumskyblue","airforceblue","smokeytopaz","ruddypink","alloyorange","fielddrab","pictorialcarmine","clear","imperialpurple","mulberry","blackbean","americanrose","schoolbusyellow","deepcarmine","mediumtuscanred","brickred","lavenderblue","sanddune","darkpastelblue","silvergray","cyberyellow","asphalt","burntumber","sheengreen","neonorange","lightapricot","palemagenta","blackolive","glaucous","oldburgundy","persianred","dogwoodrose","liberty","coralgreen","pearlypurple","mintgreen","sapgreen","britishracinggreen","cornellred","deepchampagne","pinkbeige","rackley","blue-cream","papayawhip","spacecadet","black","heathergrey","carmine","persianpink","silversand","firebrick","pastelgreen","viridiangreen","indianred","lightmediumorchid","lightbeige","dandelion","mauvetaupe","transparentdarkgreen","ceil","darkblue-gray","amazon","zaffre","atomictangerine","bistrebrown","ceruleanfrost","auburn","gradientblack","tuscanred","anti-flashwhite","gray","darkturquoise","champagne","paleblue","checkeredwhite","coquelicot","diamond","darkbyzantium","slateblue","topaz","pastelpink","alabamacrimson","xanadu","midori","falured","arcticblue","folly","columbiablue","tangelo","debianred","jade","yaleblue","skobeloff","grey","lion","darkcandyapplered","thistle","violet","silverlakeblue","outerspace","hanblue","spanishblue","persiangreen","budgreen","honeydew","cornflowerblue","classicrose","strawberry","darkblue","pinkindigo","carnationpink","venetianred","icterine","babyblue","raspberryglace","mediumred-violet","prune","oucrimsonred","richlilac","darkcoffee","barbiepink","acidblue","darkcyan","tealblue","mediumlavendermagenta","sapphire","tangopink","brown-cream","feldspar","ashblack","white","darkred","grannysmithapple","zinnwalditebrown","umber","brilliantrose","bronze","pastelmagenta","antiquefuchsia","spanishcrimson","darkterracotta","wenge","sunsetorange","bottlegreen","candyapplered","aqua","englishgreen","persianorange","parisgreen","keppel","multicolor","queenpink","berry","cybergrape","darkpastelpurple","darkpink","lightsteelblue","spanishgray","frenchraspberry","armygreen","imperialblue","duststorm","darkcerulean","leopardprint","avocado","celeste","olivedrab","peru","rosevale","otterbrown","superpink","lightfuchsiapink","stormcloud","arsenic","cosmiclatte","royalfuchsia","turquoisegreen","brightturquoise","rosebonbon","deepruby","fulvous","vermilion","purewhite","indiagreen","cadmiumorange","spanishbistre","darkpowderblue","vividorchid","uclagold","aquamarine","neonpink","moonstoneblue","caputmortuum","amaranthpink","robineggblue","bananamania","indianyellow","mediumchampagne","royalpurple","deer","aero","onyx","rosered","lawngreen","thulianpink","turquoise-purple","cottoncandy","phlox","liver","upsdellred","taupegray","congopink","ruby","offwhite","mediumpersianblue","oldlavender","red-orange","hotmagenta","scarlet","etonblue","pastelpurple","vanilla","blue-green","cherryblossompink","sunray","fallow","neonblue","celadongreen","taupe","brightlavender","newspaper","officegreen","fluorescentgreen","deeplemon","russiangreen","lighttaupe","cheddaryellow","cheetahprint","palecopper","wildstrawberry","shampoo","darkgoldenrod","tealdeer","lust","maygreen","sandybrown","mantis","beaver","windsortan","frenchrose","lightorchid","heartgold","ceruleanblue","lightcornflowerblue","deepfuchsia","englishred","darkorange","yellow","eggshell","lava","darkbrown","naplesyellow","toolbox","rosybrown","matteblack","resolutionblue","brightpink","egyptianblue","deepspacesparkle","palegoldenrod","whitegold","cocoabrown","carminered","castletongreen","mardigras","vividburgundy","bitterlemon","antiquebrass","springgreen","lightwinered","orchidpink","tealgreen","electriccyan","lemon","lemonmeringue","purple-cream","sonicsilver","phthaloblue","paleviolet-red","eucalyptus","tuscany","battleshipgrey","lavenderblush","frenchwine","waterspout","cadetgrey","electriclavender","champagne-orange","royalyellow","palelavender","napiergreen","royalazure","sinopia","rosequartz","seagreen","turquoiseblack","snowwhite","mediumpurple","harlequin","indigo","camel","emerald","checkeredred","sepia","darkolivegreen","saffron","lavenderrose","tuscanbrown","celerygreen","harvardcrimson","satinsheengold","fuchsiapink","oriolesorange","floralprint","bondiblue","aureolin","cherry","b'dazzledblue","mediumorchid","bittersweetshimmer","ultrapink","silver","grullo","chartreuse","mediumslateblue","deepsaffron","modebeige","lightcrimson","neonyellow","denim","peach-orange","alaskablue","turquoise","persianindigo","turkishrose","lavendergray","silvergrey","mauvelous","ultramarine","sapphireblue","manatee","livid","mediumvermilion","oldrose","uared","shadow","boysenberry","deeplilac","pearlaqua","midnightgreen","desire","trueblue","frenchpuce","darkgreen","cgred","electriccrimson","viridian","nude","darkviolet","saddlebrown","tigerprint","darkpurple","tyrianpurple","shimmeringblush","crystalclear","spanishskyblue","buff","goldenbrown","blackleatherjacket","eggplant","burntsienna","babypowder","tearose","lakegreen","mauve","metallicsunburst","guppiegreen","palerobineggblue","earthyellow","majorelleblue","metallicgold","hanpurple","irresistible","rosemadder","deepjunglegreen","frenchmauve","purple","cerisepink","darkmossgreen","smitten","warmblack","salmonpink","popstar","pinklace","piggypink","bisque","kellygreen","palegreen","babyblueeyes","khaki","bole","electricpurple","bluewash","corn","razzledazzlerose","byzantium","wisteria","fluorescencegreen","jazzberryjam","vividskyblue","mexicanpink","ferngreen","warmyellow","bazaar","ochre","metallicseaweed","iris","cedarchest","coralred","blueyonder","ube","coral","neoncarrot","electricyellow","cinnabar","orangelight","palegold","calpolygreen","beige","ashgrey","seashell","azure","oceanblue","oldlace","amber","cadet","citron","charmpink","rustyred","unitednationsblue","drab","bitterlime","lightrose","antiqueruby","jasper","lightcoral","deepchestnut","rosegold","nyanza","maize","chocolatebrown","fluorescentblue","paleaqua","coolblack","mediumspringgreen","usafablue","fuchsia","blanchedalmond","dartmouthgreen","bigdipo'ruby","deepcarminepink","citrine","goldenpoppy","electricblue","irishgreen","spanishcarmine","ivory","oxfordblue","brunswickgreen","palecornflowerblue","pinklight","spanishviridian","starcommandblue","lightthulianpink","forestgreen","darkpastelred","palesilver","aeroblue","lightpastelpurple","selectiveyellow","ruber","woodbrown","apricot","brightblue","daffodil","junglegreen","flirt","brilliantlavender","bubblegumpink","pastelgray","oldgold","cerulean","antiquegold","darkslategray","rust","turquoiseblue","prussianblue","russet","msugreen","charcoal","pinegreen","warmwhite","bronzeyellow","maroon","deepmauve","lavenderpink","blizzardblue","africanpurple","deeppeach","meatbrown","charlestongreen","isabelline","blast-offbronze","newyorkpink","transparentpink","cream","abyss","redblack","fuzzywuzzy","darkmidnightblue","inchworm","peach","ballblue","dimgray","redwood","bubblegum","blackgray","junebud","mediumaquamarine","chineseviolet","palatinateblue","beaublue","orchid","watermelonred","peakgreen","urobilin","waterwavecamouflage","quartz","mustard","darkorchid","teal","chinesered","ghostwhite","mellowyellow","deepcarrotorange","lightcoffee","vanillaice","grassgreen","celadonblue","bluelightwash","brass","fluorescentyellow","desert","myrtlegreen","pakistangreen","darklava","vividtangerine","verdigris","spirodiscoball","brown-nose","navyblue","lightmossgreen","arylideyellow","twilightlavender","davy'sgrey","mediumcandyapplered","blackwhite"];

var otherColorDataA = ["Fawn","French lilac","Dark raspberry","Pink lavender","Copper penny","Bright navy blue","Chamoisee","Pale plum","Forest camouflage","Olive","Dark sea green","French beige","Metallic Bronze","Rose taupe","Dark chestnut","Orange peel","Desert sand","Light khaki","Pale brown","Mint cream","Grape","Gold","Fashion fuchsia","Mountain Meadow","Dutch white","Fushcia","UCLA Blue","Lapis lazuli","Telemagenta","China pink","Neon red","Illuminating Emerald","Rhythm","Dark spring green","Crimson","Islamic green","Regalia","Pastel red","Greyish white","Dark lavender","Brown","Green-yellow","Imperial red","Barn red","Matte White","Outrageous Orange","Carrot orange","Veronica","Fluorescent orange","Dark taupe","Portland Orange","Tangerine yellow","Cyan","Bubbles","Cobalt","Peridot","Rich electric blue","Sky blue","French sky blue","Little boy blue","Brink pink","Asparagus","Dark gray","Medium spring bud","Moccasin","Platinum","Light pink","Sand","Caribbean green","Red","North Texas Green","Purple taupe","Bulgarian rose","Olivine","Claret","Purple fuchsia","Japanese indigo","Steel Blue-Purple","China rose","Light goldenrod yellow","Almond","Deep coffee","Lavender","Wild blue yonder","Neon green","Wheat","Stil de grain yellow","Blue","Yellow Orange","New Car","Magnolia","Zebra print","Sangria","Burgundy","Purplish red","Rosso corsa","Chrome yellow","Carolina blue","Pink Sherbet","Rust brown","French lime","KU Crimson","Deep cerise","Deep sky blue","Sunglow","Puce red","Dark vanilla","Nadeshiko pink","Bright cerulean","Yankees blue","Kenyan copper","Jasmine","Mountbatten pink","Lemon lime","Red-brown","Russian violet","UFO Green","Old mauve","Rose ebony","Cadmium green","Electric violet","Flavescent","Purple mountain majesty","Floral white","Yellow camouflage","Vivid violet","Flamingo pink","Metallic Silver","Azure mist","Gray-blue","Cinnamon","Antique bronze","Light red ochre","Pale spring bud","Sacramento State green","Deep moss green","Mughal green","Lemon curry","Golden","Ruby red","Spartan Crimson","Green plaid","Straw","French bistre","Light sea green","Purple Heart","Off-white","Sienna","Vivid cerise","Skyblue Orange","Purple pizzazz","Raw umber","Cameo pink","Rosewood","Gamboge","Copper red","Ebony","Lime","White Dye Dip","Princeton orange","Shocking pink","Blue sapphire","Wine red","Royal blue","Lake blue","Lavender magenta","Tuscan","Pearl","Capri","French blue","Fresh Air","Pale carmine","Blueberry","Cerise","Chestnut","Blue-gray","Bright green","Light yellow","Mikado yellow","Pastel violet","Tangerine","Flax","Lemon chiffon","Chocolate","Melon","Cordovan","Aqua blue","Dark grey","Psychedelic purple","Catawba","Medium carmine","Fandango pink","Dark tangerine","Silver green","Antique white","Tiger's eye","Pale taupe","Baker-Miller pink","Patriarch","Dark slate blue","Light sky blue","Sandstorm","Rufous","Lumber","Languid lavender","Deep pink","Fandango","Pumpkin","Plum","Pale red-violet","Bittersweet","Timberwolf","Pale turquoise","Light brown","Dodger blue","Honolulu blue","Liver chestnut","Navy purple","Magenta","Tan","Medium ruby","Pink","Purple light","Vivid auburn","Black fuchsia","Safety yellow","Pistachio","Persimmon","Jelly Bean","Khaki Green","Orange-red","Mellow apricot","Giants orange","Mango Tango","Cardinal","Rose","Cheetah","Pale cerulean","Midnight blue","Rich carmine","Coral pink","Purple navy","Yellow rose","Dark jungle green","Transparent White","Bright ube","Mordant red 19","Non-photo blue","Dark liver","Fuchsia-Black","Light slate gray","Opera mauve","Floral","Magenta haze","Japanese violet","Camel brown","Rubine red","Medium sea green","Light gray","Smoke","Heliotrope","Tractor red","Cadet blue","Blue Bell","Ultramarine blue","Maya blue","Silver white","Ruddy brown","Tickle Me Pink","Linen","Light leopard","Green","Light tan","Powder blue","Bluebonnet","Tiffany Blue","Peach puff","Cherry Pink","Wine","Baby pink","Kombu green","Medium violet-red","Tuscan tan","Dark coral","Smoky black","Nacarat","Yellow-green","Italian sky blue","USC Cardinal","Violet-red","Sandy taupe","Electric indigo","Cambridge Blue","Khaki Beige","Lavender mist","Dark imperial blue","Shamrock green","Indigo dye","Razzmatazz","Malachite","Screamin' Green","Silver pink","Seal brown","Medium blue","Electric lime","Orange","Lincoln green","La Salle Green","Canary yellow","Antique Black","Smalt","Coffee","Lemon yellow","AuroMetalSaurus","Brandeis blue","Pink pearl","English violet","Moss green","UP Maroon","Pastel orange","Dollar bill","Pink-orange","Wine dregs","Persian rose","Wild orchid","Fuchsia rose","Jonquil","Pastel yellow","Cocoa","Candy pink","Goldenrod","Catalina blue","UA blue","Razzmic Berry","Tiger","Sunset","Bright maroon","Duke blue","Ecru","Deep Taupe","Radical Red","Safety orange","Wild Watermelon","Dark magenta","Apple green","Utah Crimson","Old moss green","Bone","Bright red","Hansa yellow","Tumbleweed","Pastel blue","Lilac","Red devil","Mahogany","Orange plaid","Generic viridian","Medium turquoise","Multicolored","Medium taupe","Zebra","Queen blue","Navy","Cadmium yellow","Trolley Grey","Ocean Boat Blue","Sandy","Celestial blue","Olive green","Dark army green","Dark plum","Navajo white","Deep Tuscan red","Milk white","Rich lavender","Hunter green","Light purple","Dark khaki","Palatinate purple","Sea blue","Stizza","Peach-yellow","Amaranth","Amethyst","Steel pink","USC Gold","Light carmine pink","Cornsilk","Independence","Ruddy","Slate gray","Ferrari Red","Donkey Brown","Acid green","Dirt","Leopard","Bistre","Paolo Veronese green","Crimson glory","Steel blue","Gray-asparagus","Magic mint","Rose pink","Carnelian","Alice blue","Copper rose","Schauss pink","Gainsboro","Water blue","Rifle green","Feldgrau","Phthalo green","Pale pink","Ink blue","Light grey","Light cyan","Alizarin crimson","Dark salmon","Rocket metallic","Bleu de France","Lavender purple","Blush","Medium jungle green","Tea green","Burnt orange","Copper","Puce","Unmellow yellow","Licorice","Limerick","Tufts Blue","Cool grey","Misty rose","UP Forest green","Kobi","Amber gold","Electric green","Dark sienna","Kobe","Eminence","Imperial","Glitter","Sky magenta","Dark yellow","Lavender indigo","Hollywood cerise","Jet","Spring bud","Burlywood","Red-violet","Terra cotta","Carmine pink","Rich black","Electric ultramarine","Camouflage green","Laser Lemon","Spanish orange","Periwinkle","Cinereous","Purpureus","Transparent red","Dark sky blue","Tomato","Dark tan","Cadmium red","Laurel green","Neon fuchsia","Heather Gray","Pale chestnut","English lavender","Denim blue","Green Apple","Green light","Light salmon","Rich maroon","Flattery","Dark electric blue","Iceberg","Hot pink","Raspberry","Lime green","Dark pastel green","Pear","Peacock blue","Celadon","Dark scarlet","Blue-violet","Flame","Fire engine red","Gold Fusion","Light salmon pink","Golden yellow","Coconut","Persian blue","Titanium yellow","Android green","Washed black","Pansy purple","Olive green black","Ginger","Payne's grey","Light green","Persian plum","Blond","CG Blue","Roman silver","Mint","Pastel brown","Byzantine","White smoke","Light blue","Violet-blue","Rich brilliant lavender","Fluorescent rose","Raspberry rose","Tulip","Deep magenta","Vegas gold","Snow","Camouflage","Tropical rain forest","Medium electric blue","Banana yellow","Rajah","Zomp","Fluorescent pink","Raspberry pink","Unbleached silk","Soap","Transparent","Yellow light","Silver chalice","Lemon glacier","Old silver","Salmon","Antique silver","Harvest gold","Medium sky blue","Air Force blue","Smokey topaz","Ruddy pink","Alloy orange","Field drab","Pictorial carmine","Clear","Imperial purple","Mulberry","Black bean","American rose","School bus yellow","Deep carmine","Medium Tuscan red","Brick red","Lavender blue","Sand dune","Dark pastel blue","Silver gray","Cyber yellow","Asphalt","Burnt umber","Sheen Green","Neon orange","Light apricot","Pale magenta","Black olive","Glaucous","Old burgundy","Persian red","Dogwood rose","Liberty","Coral green","Pearly purple","Mint green","Sap green","British racing green","Cornell Red","Deep champagne","Pink Beige","Rackley","Blue-Cream","Papaya whip","Space cadet","Black","Heather grey","Carmine","Persian pink","Silver sand","Firebrick","Pastel green","Viridian green","Indian red","Light medium orchid","Light beige","Dandelion","Mauve taupe","Transparent dark green","Ceil","Dark blue-gray","Amazon","Zaffre","Atomic tangerine","Bistre brown","Cerulean frost","Auburn","Gradient black","Tuscan red","Anti-flash white","Gray","Dark turquoise","Champagne","Pale blue","Checkered White","Coquelicot","Diamond","Dark byzantium","Slate blue","Topaz","Pastel pink","Alabama crimson","Xanadu","Midori","Falu red","Arctic blue","Folly","Columbia blue","Tangelo","Debian red","Jade","Yale Blue","Skobeloff","Grey","Lion","Dark candy apple red","Thistle","Violet","Silver Lake blue","Outer Space","Han blue","Spanish blue","Persian green","Bud green","Honeydew","Cornflower blue","Classic rose","Strawberry","Dark blue","Pink indigo","Carnation pink","Venetian red","Icterine","Baby blue","Raspberry glace","Medium red-violet","Prune","OU Crimson Red","Rich lilac","Dark coffee","Barbie pink","Acid blue","Dark cyan","Teal blue","Medium lavender magenta","Sapphire","Tango pink","Brown-Cream","Feldspar","Ash black","White","Dark red","Granny Smith Apple","Zinnwaldite brown","Umber","Brilliant rose","Bronze","Pastel magenta","Antique fuchsia","Spanish crimson","Dark terra cotta","Wenge","Sunset orange","Bottle green","Candy apple red","Aqua","English green","Persian orange","Paris Green","Keppel","Multicolor","Queen pink","Berry","Cyber grape","Dark pastel purple","Dark pink","Light steel blue","Spanish gray","French raspberry","Army green","Imperial blue","Dust storm","Dark cerulean","Leopard print","Avocado","Celeste","Olive Drab","Peru","Rose vale","Otter brown","Super pink","Light fuchsia pink","Stormcloud","Arsenic","Cosmic latte","Royal fuchsia","Turquoise green","Bright turquoise","Rose bonbon","Deep ruby","Fulvous","Vermilion","Pure white","India green","Cadmium orange","Spanish bistre","Dark powder blue","Vivid orchid","UCLA Gold","Aquamarine","Neon pink","Moonstone blue","Caput mortuum","Amaranth pink","Robin egg blue","Banana Mania","Indian yellow","Medium champagne","Royal purple","Deer","Aero","Onyx","Rose red","Lawn green","Thulian pink","Turquoise-Purple","Cotton candy","Phlox","Liver","Upsdell red","Taupe gray","Congo pink","Ruby","Off white","Medium Persian blue","Old lavender","Red-orange","Hot magenta","Scarlet","Eton blue","Pastel purple","Vanilla","Blue-green","Cherry blossom pink","Sunray","Fallow","Neon blue","Celadon green","Taupe","Bright lavender","Newspaper","Office green","Fluorescent green","Deep lemon","Russian green","Light taupe","Cheddar Yellow","Cheetah print","Pale copper","Wild Strawberry","Shampoo","Dark goldenrod","Teal deer","Lust","May green","Sandy brown","Mantis","Beaver","Windsor tan","French rose","Light orchid","Heart Gold","Cerulean blue","Light cornflower blue","Deep fuchsia","English red","Dark orange","Yellow","Eggshell","Lava","Dark brown","Naples yellow","Toolbox","Rosy brown","Matte Black","Resolution blue","Bright pink","Egyptian blue","Deep Space Sparkle","Pale goldenrod","White gold","Cocoa brown","Carmine red","Castleton green","Mardi Gras","Vivid burgundy","Bitter lemon","Antique brass","Spring green","Light wine red","Orchid pink","Teal green","Electric cyan","Lemon","Lemon meringue","Purple-Cream","Sonic silver","Phthalo blue","Pale violet-red","Eucalyptus","Tuscany","Battleship grey","Lavender blush","French wine","Waterspout","Cadet grey","Electric lavender","Champagne-Orange","Royal yellow","Pale lavender","Napier green","Royal azure","Sinopia","Rose quartz","Sea green","Turquoise black","Snow White","Medium purple","Harlequin","Indigo","Camel","Emerald","Checkered Red","Sepia","Dark olive green","Saffron","Lavender rose","Tuscan brown","Celery green","Harvard crimson","Satin sheen gold","Fuchsia pink","Orioles orange","Floral print","Bondi blue","Aureolin","Cherry","B'dazzled blue","Medium orchid","Bittersweet shimmer","Ultra pink","Silver","Grullo","Chartreuse","Medium slate blue","Deep saffron","Mode beige","Light crimson","Neon yellow","Denim","Peach-orange","Alaska blue","Turquoise","Persian indigo","Turkish rose","Lavender gray","Silver grey","Mauvelous","Ultramarine","Sapphire blue","Manatee","Livid","Medium vermilion","Old rose","UA red","Shadow","Boysenberry","Deep lilac","Pearl Aqua","Midnight green","Desire","True Blue","French puce","Dark green","CG Red","Electric crimson","Viridian","Nude","Dark violet","Saddle brown","Tiger print","Dark purple","Tyrian purple","Shimmering Blush","Crystal Clear","Spanish sky blue","Buff","Golden brown","Black leather jacket","Eggplant","Burnt sienna","Baby powder","Tea rose","Lake green","Mauve","Metallic Sunburst","Guppie green","Pale robin egg blue","Earth yellow","Majorelle Blue","Metallic Gold","Han purple","Irresistible","Rose madder","Deep jungle green","French mauve","Purple","Cerise pink","Dark moss green","Smitten","Warm black","Salmon pink","Popstar","Pink lace","Piggy pink","Bisque","Kelly green","Pale green","Baby blue eyes","Khaki","Bole","Electric purple","Blue Wash","Corn","Razzle dazzle rose","Byzantium","Wisteria","Fluorescence green","Jazzberry jam","Vivid sky blue","Mexican pink","Fern green","Warm Yellow","Bazaar","Ochre","Metallic Seaweed","Iris","Cedar Chest","Coral red","Blue yonder","Ube","Coral","Neon Carrot","Electric yellow","Cinnabar","Orange light","Pale gold","Cal Poly green","Beige","Ash grey","Seashell","Azure","Ocean blue","Old lace","Amber","Cadet","Citron","Charm pink","Rusty red","United Nations blue","Drab","Bitter lime","Light rose","Antique ruby","Jasper","Light coral","Deep chestnut","Rose gold","Nyanza","Maize","Chocolate brown","Fluorescent blue","Pale aqua","Cool black","Medium spring green","USAFA blue","Fuchsia","Blanched almond","Dartmouth green","Big dip o'ruby","Deep carmine pink","Citrine","Golden poppy","Electric blue","Irish green","Spanish carmine","Ivory","Oxford Blue","Brunswick green","Pale cornflower blue","Pink light","Spanish viridian","Star command blue","Light Thulian pink","Forest green","Dark pastel red","Pale silver","Aero blue","Light pastel purple","Selective yellow","Ruber","Wood brown","Apricot","Bright blue","Daffodil","Jungle green","Flirt","Brilliant lavender","Bubblegum Pink","Pastel gray","Old gold","Cerulean","Antique Gold","Dark slate gray","Rust","Turquoise blue","Prussian blue","Russet","MSU Green","Charcoal","Pine green","Warm white","Bronze Yellow","Maroon","Deep mauve","Lavender pink","Blizzard Blue","African purple","Deep peach","Meat brown","Charleston green","Isabelline","Blast-off bronze","New York pink","Transparent pink","Cream","Abyss","Red black","Fuzzy Wuzzy","Dark midnight blue","Inchworm","Peach","Ball blue","Dim gray","Redwood","Bubble gum","Black gray","June bud","Medium aquamarine","Chinese violet","Palatinate blue","Beau blue","Orchid","Watermelon red","Peak green","Urobilin","Water wave camouflage","Quartz","Mustard","Dark orchid","Teal","Chinese red","Ghost white","Mellow yellow","Deep carrot orange","Light coffee","Vanilla ice","Grass green","Celadon blue","Blue Light Wash","Brass","Fluorescent yellow","Desert","Myrtle green","Pakistan green","Dark lava","Vivid tangerine","Verdigris","Spiro Disco Ball","Brown-nose","Navy blue","Light moss green","Arylide yellow","Twilight lavender","Davy's grey","Medium candy apple red","Black white"];
