CREATE TABLE IF NOT EXISTS `rumall_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `Remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `SfOrderType` varchar(50) DEFAULT NULL COMMENT '顺丰订单类型',
  `ErpOrder` varchar(255) NOT NULL COMMENT '订单号',
  `OrderNote` varchar(255) DEFAULT NULL COMMENT '订单备注',
  `PackageNote` varchar(255) DEFAULT NULL COMMENT '包装备注',
  `TradeOrderDateTime` datetime DEFAULT NULL COMMENT '订单日期(下单日期)',
  `PayDateTime` datetime DEFAULT NULL COMMENT '付款日期',
  `CurrencyCode` varchar(20) NOT NULL COMMENT '币种代码',
  `CompanyNote` varchar(255) DEFAULT NULL COMMENT '商家备注',
  `ShopName` varchar(55) NOT NULL COMMENT '店铺名称',
  `TradePlatform` varchar(55) DEFAULT NULL COMMENT '交易平台',
  `TradeOrder` varchar(255) DEFAULT NULL COMMENT '平台交易号',
  `BuyerId` varchar(55) NOT NULL COMMENT '买家账号',
  `DeliveryDate` datetime DEFAULT NULL COMMENT '发货日期',
  `PaymentMethod` varchar(55) DEFAULT NULL COMMENT '客户支付方式',
  `PaymentNumber` varchar(55) DEFAULT NULL COMMENT '支付号码',
  `Freight` decimal(10,2) DEFAULT NULL COMMENT '订单支付运费',
  `DiscountRate` decimal(10,2) DEFAULT '0.00',
  `OrderTotalAmount` decimal(10,2) DEFAULT NULL COMMENT '订单总金额',
  `OrderDiscount` decimal(10,2) DEFAULT NULL COMMENT '订单优惠金额',
  `OtherCharge` decimal(10,2) DEFAULT '0.00' COMMENT '其他金额',
  `balance_amount` decimal(10,2) DEFAULT '0.00' COMMENT '余额支付金额',
  `is_appoint_delivery` char(2) DEFAULT NULL COMMENT '是否预约',
  `appoint_delivery_status` varchar(55) DEFAULT NULL COMMENT '预约状态',
  `appoint_delivery_remark` varchar(255) DEFAULT NULL COMMENT '预约备注',
  `order_url` varchar(255) DEFAULT NULL COMMENT '商品网址',
  `order_website` varchar(255) DEFAULT NULL COMMENT '平台网址',
  `ActualAmount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实际支付金额',
  `DeliveryModel` varchar(50) DEFAULT NULL COMMENT '订单发货模式',
  `IsAllowSplit` char(2) DEFAULT NULL COMMENT '是否允许拆单',
  `ReceiverCompany` varchar(255) DEFAULT NULL COMMENT '收件方公司',
  `ReceiverName` varchar(255) DEFAULT NULL COMMENT '收件方名称',
  `ReceiverEmail` varchar(255) DEFAULT NULL COMMENT '收件方电子邮箱',
  `ReceiverZipCode` varchar(55) DEFAULT NULL COMMENT '收件方邮编',
  `ReceiverMobile` varchar(55) DEFAULT NULL COMMENT '收件方手机',
  `ReceiverPhone` varchar(55) DEFAULT NULL COMMENT '收件方电话',
  `CountryCode` char(5) DEFAULT NULL COMMENT '收件人国家代码',
  `ConsigneeFullname` varchar(255) DEFAULT NULL COMMENT '收件人全名',
  `ReceiverCountry` varchar(255) DEFAULT NULL COMMENT '收件方国家',
  `ReceiverProvince` varchar(255) DEFAULT NULL COMMENT '收件方省份',
  `ReceiverCity` varchar(255) DEFAULT NULL COMMENT '收件方城市',
  `ReceiverArea` varchar(255) DEFAULT NULL COMMENT '收件方区县',
  `ReceiverAddress` varchar(255) DEFAULT NULL COMMENT '收件方地址',
  `ConsigneeStreet` varchar(255) DEFAULT NULL COMMENT '所在街道',
  `ConsigneeDoorplate` varchar(255) DEFAULT NULL COMMENT '门牌号',
  `ReceiverIdType` varchar(255) DEFAULT NULL COMMENT '收件方证件类型',
  `ReceiverIdCard` varchar(255) DEFAULT NULL COMMENT '收件方证件号码',
  `OrderSenderInfo` text COMMENT '寄方信息',
  `order_detail` text COMMENT '整张订单的所有信息',
  `addinfo` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=21 ;


CREATE TABLE IF NOT EXISTS `rumall_order_detail` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `orderID` varchar(255) NOT NULL,
  `ErpOrderLineNum` varchar(255) DEFAULT NULL COMMENT '行号',
  `SkuNo` varchar(55) DEFAULT NULL COMMENT '商品编码',
  `ItemName` varchar(255) DEFAULT NULL COMMENT '商品简名称',
  `ItemImage` varchar(255) DEFAULT NULL,
  `ItemOldName` varchar(255) DEFAULT NULL COMMENT '商品详细名称',
  `ItemUom` varchar(55) DEFAULT NULL COMMENT '商品单位',
  `ItemQuantity` int(11) DEFAULT '0' COMMENT '商品数量',
  `ItemPrice` decimal(10,2) DEFAULT '0.00' COMMENT '商品单价',
  `ItemDiscount` decimal(10,2) DEFAULT NULL COMMENT '商品优惠金额',
  `CheckPrepardNo` varchar(55) DEFAULT NULL COMMENT '商品国检备案编号',
  `CustomsPrepardNo` varchar(55) DEFAULT NULL COMMENT '商品海关备案号',
  `HsCode` varchar(55) DEFAULT NULL COMMENT '海关编号',
  `ItemBrand` varchar(55) DEFAULT NULL COMMENT '商品品牌',
  `ItemSpecifications` varchar(55) DEFAULT NULL COMMENT '商品型号',
  `BomAction` varchar(55) DEFAULT NULL COMMENT '是否组合商品',
  `IsPresent` varchar(55) DEFAULT NULL COMMENT '是否赠品',
  `IsVirtualProduct` varchar(55) DEFAULT NULL COMMENT '是否虚拟增值产品',
  `InventoryStatus` varchar(55) DEFAULT NULL COMMENT '库存类型',
  `Lot` varchar(55) DEFAULT NULL COMMENT '批号',
  `Note` varchar(55) DEFAULT NULL COMMENT '明细备注',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=6 ;

CREATE TABLE IF NOT EXISTS `rumall_orders_history` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `store_name` varchar(255) NOT NULL COMMENT '店铺名',
  `orderId` varchar(55) NOT NULL COMMENT '原始订单号',
  `order_detail` text NOT NULL COMMENT '原始订单内容',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;